### ISSUE TITLE
Cloned repo will not load in Android Studio.

### ISSUE THREAD

**Issue by RobRoseKnows** [MBHS-SPC/speed-trig-android#5]
I cloned the repo because I wanted to get some work done on it. Unfortunately every time I clone the repo it gives me a file structure with a bunch of seemingly pointless folders before actually reaching the source code. In Android Studio however, when I open up the project it only shows the readme and gitignore files. I assume others have had a similar issue and solved it so I wanted to know what the hell is set up wrong in the repo and how I can fix it.

**Comment by eyob--** [comment]
That's not your fault, it's a result of multiple reincarnations of the same project. I will get that fixed ASAP

**Comment by RobRoseKnows** [comment]
Alright. I wanted to work on it a little bit but you'll definitely want to make sure it's done so that other club members can access it.

**Comment by eyob--** [comment]
Ok, cool. Done with the cleanup. You can import the project by doing File -> New -> Project From Version Control -> GitHub. You'll also want to do the little "Import Gradle Project" after it finishes loading and choose the default build.gradle. Once that's done, it should be all good. If you open a java file and get a bunch of red lines, you can fix that by just running the program once. I'm pretty sure a Build -> Make Project will also fix that.

**Comment by RobRoseKnows** [comment]
Can confirm that it works now.
